/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.projektfiler;

import SQLHanterare.ProjektHanterare;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import orgEntities.Projekt;
import gui.Meny;
import gui.projektruta;


/**
 *
 * @author theow
 */
public class OneProjectView extends javax.swing.JFrame {
    
    private Projekt projekt;
    private String[] kolumnNamn;
    private Object[] rad;
    private OneProjectView oneProjectView;
    
    

    /**
     * Creates new form projektInfo
     * @param projekt is a project to be displayed on this page.
     */
    public OneProjectView(String pid) {
        
        oneProjectView = this;
        ProjektHanterare projektHanterare = new ProjektHanterare(pid);
        Projekt projekt = new Projekt(projektHanterare);
        
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        String[] projInfo;
        this.projekt = projekt;
        String[] kolumnNamn = new String[] {
            "Pid", 
            "Projektnamn", 
            "Beskrivning", 
            "Startdatum", 
            "Slutdatum",
            "Kostnad",
            "Status",
            "Prioritet",
            "Projektchef",
            "land"
         };
        
        this.kolumnNamn = kolumnNamn;
        
         this.fillTable();
         
    }


    
    public void fillTable() {
        
    this.updateTable();
    
    rad = new Object[]{
    projekt.getPid(),
    projekt.getProjektnamn(),
    projekt.getBeskrivning(),
    projekt.getStartdatum(),
    projekt.getSlutdatum(),
    projekt.getKostnad(),
    projekt.getStatus(),
    projekt.getPrioritet(),
    projekt.getProjektchef(),
    projekt.getLand(),
  
    };
        
    DefaultTableModel nyModel = new DefaultTableModel(kolumnNamn, 0);
    nyModel.addRow(rad);
    jTable1.setModel(nyModel);   
    
    
 
 }
    
    public void updateTable() {
    
    ProjektHanterare projektHanterare = new ProjektHanterare(projekt.getPid());
    this.projekt = new Projekt(projektHanterare);
    DefaultTableModel nyModel = (DefaultTableModel) jTable1.getModel();
    nyModel.setRowCount(0);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projektInfo = new javax.swing.JPanel();
        lblEditProject = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblInsikter = new javax.swing.JLabel();
        lbllProjName1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnTillbakaTillProjektRuta = new javax.swing.JToggleButton();
        lblPartners = new javax.swing.JLabel();
        lblEkonomi1 = new javax.swing.JLabel();
        lblTeam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(854, 480));

        projektInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEditProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pen32.png"))); // NOI18N
        lblEditProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEditProjectMouseClicked(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(29, 29, 29));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jTable1.setDoubleBuffered(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout projektInfoLayout = new javax.swing.GroupLayout(projektInfo);
        projektInfo.setLayout(projektInfoLayout);
        projektInfoLayout.setHorizontalGroup(
            projektInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projektInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEditProject)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        projektInfoLayout.setVerticalGroup(
            projektInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projektInfoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(projektInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditProject)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblInsikter.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInsikter.setText("Insikter");

        lbllProjName1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbllProjName1.setText("Projektnamn");

        jButton1.setText("Se partners");

        btnTillbakaTillProjektRuta.setBackground(new java.awt.Color(7, 96, 216));
        btnTillbakaTillProjektRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/turn-left.png"))); // NOI18N
        btnTillbakaTillProjektRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillProjektRutaActionPerformed(evt);
            }
        });

        lblPartners.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPartners.setText("Partners");

        lblEkonomi1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEkonomi1.setText("Ekonomi");

        lblTeam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTeam.setText("Team");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnTillbakaTillProjektRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projektInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lbllProjName1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(lblPartners)
                        .addGap(258, 258, 258)
                        .addComponent(lblTeam)
                        .addGap(207, 207, 207)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblInsikter)))
                .addContainerGap(1277, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(lblEkonomi1)
                    .addContainerGap(2297, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnTillbakaTillProjektRuta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lbllProjName1)
                        .addGap(18, 18, 18)
                        .addComponent(projektInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblInsikter)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPartners)
                            .addComponent(lblTeam))))
                .addContainerGap(796, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(281, 281, 281)
                    .addComponent(lblEkonomi1)
                    .addContainerGap(798, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaTillProjektRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillProjektRutaActionPerformed
        this.setVisible(false);
        projektruta proj = new projektruta();
        proj.setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillProjektRutaActionPerformed

    private void lblEditProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEditProjectMouseClicked
        String inPid = projekt.getPid();
        EditProjectFields editProjectFields = new EditProjectFields(projekt, oneProjectView);
        editProjectFields.setVisible(true);

    }//GEN-LAST:event_lblEditProjectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new OneProjectView().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnTillbakaTillProjektRuta;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEditProject;
    private javax.swing.JLabel lblEkonomi1;
    private javax.swing.JLabel lblInsikter;
    private javax.swing.JLabel lblPartners;
    private javax.swing.JLabel lblTeam;
    private javax.swing.JLabel lbllProjName1;
    private javax.swing.JPanel projektInfo;
    // End of variables declaration//GEN-END:variables
}
