/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.projektfiler;

import SQLHanterare.ProjektHanterare;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import orgEntities.Projekt;


/**
 *
 * @author theow
 */
public class OneProjectView extends javax.swing.JFrame {
    
    private Projekt projekt;
    private String[] kolumnNamn;
    private Object[] rad;
    

    /**
     * Creates new form projektInfo
     * @param projekt is a project to be displayed on this page.
     */
    public OneProjectView(Projekt projekt) {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        String[] projInfo;
        this.projekt = projekt;
        String[] kolumnNamn = new String[] {
            "Pid", 
            "Projektnamn", 
            "Beskrivning", 
            "Startdatum", 
            "Slutdatum",
            "Kostnad",
            "Status",
            "Prioritet",
            "Projektchef",
            "land"
         };
        
        this.kolumnNamn = kolumnNamn;
        
         this.fillTable();

         
    }
        
    
    public void fillTable() {
        
    rad = new Object[]{
    projekt.getPid(),
    projekt.getProjektnamn(),
    projekt.getBeskrivning(),
    projekt.getStartdatum(),
    projekt.getSlutdatum(),
    projekt.getKostnad(),
    projekt.getStatus(),
    projekt.getPrioritet(),
    projekt.getProjektchef(),
    projekt.getLand(),
    
    };
        
    DefaultTableModel nyModel = new DefaultTableModel(kolumnNamn, 0);
    nyModel.addRow(rad);
    jTable1.setModel(nyModel);     
 
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projektInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblEditProject = new javax.swing.JLabel();
        lblInsikter = new javax.swing.JLabel();
        lbllProjName1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(854, 480));

        projektInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jTable1.setDoubleBuffered(true);
        jScrollPane1.setViewportView(jTable1);

        lblEditProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pennaikon.png"))); // NOI18N

        javax.swing.GroupLayout projektInfoLayout = new javax.swing.GroupLayout(projektInfo);
        projektInfo.setLayout(projektInfoLayout);
        projektInfoLayout.setHorizontalGroup(
            projektInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projektInfoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEditProject)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        projektInfoLayout.setVerticalGroup(
            projektInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projektInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(projektInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditProject)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblInsikter.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInsikter.setText("Insikter");

        lbllProjName1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbllProjName1.setText("Projektnamn");

        jButton1.setText("Se partners");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(lbllProjName1)
                    .addComponent(projektInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsikter))
                .addContainerGap(1220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbllProjName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(projektInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(lblInsikter)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(751, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneProjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new OneProjectView().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEditProject;
    private javax.swing.JLabel lblInsikter;
    private javax.swing.JLabel lbllProjName1;
    private javax.swing.JPanel projektInfo;
    // End of variables declaration//GEN-END:variables
}
