/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import orgEntities.*;
import SQLHanterare.*;
import gui.*;

        

/**
 *
 * @author theow
 */
public class EditLand extends javax.swing.JFrame {
   
    Lander lander;
    LandHanterare lh;
    Land land;
    String lid;
          
    

    public EditLand(Land land) {
        this.land = land;
        lid = land.getLid();

        initComponents();
        this.setTextBoxes();
  
        // metoden nedan är tilllagt nu
        lh = new LandHanterare(lid);
        
    }


    public void setTextBoxes() {

        txtNamn.setText(land.getNamn());
        this.fillComboBoxes();

}
    /**
     * I sin nuvarande form hämtar inte metoden information från projektet som ska redigeras, utan läggar bara till i comboboxarna de alternativ som finns i databasen.
     */
    public void fillComboBoxes() { 
    // Fill Språk
        
        comboSprak.removeAllItems();        
        comboSprak.addItem("Sprak 1");
        comboSprak.addItem("Sprak 2");
        comboSprak.addItem("Sprak 3");
        comboSprak.addItem("Sprak 4");
        comboSprak.addItem("Sprak 5");
        comboSprak.addItem("Sprak 6");
        

        // Valuta
        comboValuta.removeAllItems();   
        comboValuta.addItem("10.1234");
        comboValuta.addItem("20.5678");
        comboValuta.addItem("30.9876");
        comboValuta.addItem("40.5432");
        comboValuta.addItem("50.8765");
        comboValuta.addItem("60.4321");


        
        // FIll Tidszon 
        comboTidszon.removeAllItems(); 
        comboTidszon.addItem("Tidszon 1");
        comboTidszon.addItem("Tidszon 2");
        comboTidszon.addItem("Tidszon 3");
        comboTidszon.addItem("Tidszon 4");
        comboTidszon.addItem("Tidszon 5");
        comboTidszon.addItem("Tidszon 6");


        
        // Fill politisk struktur
        comboPolStru.removeAllItems(); 
        comboPolStru.addItem("Politisk struktur 1");
        comboPolStru.addItem("Politisk struktur 2");
        comboPolStru.addItem("Politisk struktur 3");
        comboPolStru.addItem("Politisk struktur 4");
        comboPolStru.addItem("Politisk struktur 5");
        comboPolStru.addItem("Politisk struktur 6");

        
        // Fill ekonomi
        comboEkonomi.removeAllItems(); 
        comboEkonomi.addItem("Ekonomi 1");
        comboEkonomi.addItem("Ekonomi 2");
        comboEkonomi.addItem("Ekonomi 3");
        comboEkonomi.addItem("Ekonomi 4");
        comboEkonomi.addItem("Ekonomi 5");
        comboEkonomi.addItem("Ekonomi 6");


}


    public boolean setLandInfo() {

        String namn = txtNamn.getText();
        String sprak = (String) comboSprak.getSelectedItem();
        String valuta = (String) comboValuta.getSelectedItem();
        String tidszon = (String) comboTidszon.getSelectedItem();
        String polstru = (String) comboPolStru.getSelectedItem();
        String ekonomi = (String) comboPolStru.getSelectedItem();
        
        
        if (!lh.andraNamn(lid, namn)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte uppdatera namn.");
            return false;
        }
        if (!lh.andraSprak(lid, sprak)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte uppdatera språk.");
            return false;
        }
        if (!lh.andraValuta(lid, valuta)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte uppdatera valuta.");
            return false;
        }
        if (!lh.andraTidszon(lid, tidszon)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte uppdatera tidszon.");
            return false;
        }
        if (!lh.andraPolitiskStruktur(lid, polstru)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte uppdatera politisk struktur.");
            return false;
        }
        if (!lh.andraEkonomi(lid, ekonomi)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Kunde inte uppdatera ekonomi.");
            return false;
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Uppgifterna har sparats.");
        
        return true;

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLosenord = new javax.swing.JLabel();
        lblAnsDatum = new javax.swing.JLabel();
        lblAdress = new javax.swing.JLabel();
        lblFornamn = new javax.swing.JLabel();
        lblEfternamn = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnSparaLand = new javax.swing.JButton();
        comboTidszon = new javax.swing.JComboBox<>();
        lblTelefon = new javax.swing.JLabel();
        btnTillbakaTillLand = new javax.swing.JToggleButton();
        comboPolStru = new javax.swing.JComboBox<>();
        comboSprak = new javax.swing.JComboBox<>();
        comboValuta = new javax.swing.JComboBox<>();
        comboEkonomi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblLosenord.setText("Ekonomi");

        lblAnsDatum.setText("Valuta");

        lblAdress.setText("Politisk struktur");

        lblFornamn.setText("Namn");

        lblEfternamn.setText("Språk");

        txtNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamnActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Redigera Land");

        btnSparaLand.setBackground(new java.awt.Color(7, 96, 216));
        btnSparaLand.setForeground(new java.awt.Color(255, 255, 255));
        btnSparaLand.setText("Spara");
        btnSparaLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaLandActionPerformed(evt);
            }
        });

        lblTelefon.setText("Tidszon");

        btnTillbakaTillLand.setBackground(new java.awt.Color(7, 96, 216));
        btnTillbakaTillLand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/turn-left-small.png"))); // NOI18N
        btnTillbakaTillLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillLandActionPerformed(evt);
            }
        });

        comboPolStru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSprak, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdress)
                            .addComponent(comboTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTillbakaTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(266, 266, 266)
                                .addComponent(lblTitle))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSparaLand, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblFornamn, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                            .addGap(441, 441, 441))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAnsDatum)
                                                .addComponent(lblEfternamn)
                                                .addComponent(lblTelefon)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                                    .addComponent(comboPolStru, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGap(193, 193, 193)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLosenord)
                                        .addComponent(comboEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(65, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbakaTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLosenord)
                    .addComponent(lblFornamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEfternamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAnsDatum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblTelefon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAdress)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPolStru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSparaLand, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamnActionPerformed

    private void btnSparaLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaLandActionPerformed
           if (setLandInfo()) {
           this.setVisible(false);
               
           }
          
    }//GEN-LAST:event_btnSparaLandActionPerformed

    private void btnTillbakaTillLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillLandActionPerformed
        this.setVisible(false);
        Lander land = new Lander();
        land.setVisible(true);
    }//GEN-LAST:event_btnTillbakaTillLandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EditProjectFields().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSparaLand;
    private javax.swing.JToggleButton btnTillbakaTillLand;
    private javax.swing.JComboBox<String> comboEkonomi;
    private javax.swing.JComboBox<String> comboPolStru;
    private javax.swing.JComboBox<String> comboSprak;
    private javax.swing.JComboBox<String> comboTidszon;
    private javax.swing.JComboBox<String> comboValuta;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAnsDatum;
    private javax.swing.JLabel lblEfternamn;
    private javax.swing.JLabel lblFornamn;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtNamn;
    // End of variables declaration//GEN-END:variables
}

