

package gui;
import oru.inf.InfDB;
import oru.inf.InfException;
import db.DatabaseInterface;
import gui.Meny;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicComponents.User.CurrentUser;
import logicComponents.User.User;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author amandahelinlarsson
 */
public class Hållbarhetsmål extends javax.swing.JFrame {
     private InfDB idb;
     
  
 // konstruktor
public Hållbarhetsmål(){
    initComponents(); 
    setExtendedState(MAXIMIZED_BOTH); // maximerar fönstret
    setLocationRelativeTo(null); // centrerar fönstret
    try {
    idb = DatabaseInterface.databaseConnection();
    fyllTabell();
    } catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Kunde inte ansluta till databasen");
}
}
    /**
     * Creates new form Hållbarhetsmål
     * Fyller tabellen, från databasen
     */
    private void fyllTabell(){
        try {
            String query = "SELECT hid, namn, malnummer, beskrivning, prioritet FROM hallbarhetsmal";
            ArrayList<HashMap< String, String >> hallbarhetsLista = idb.fetchRows(query);

            String [] columnNames = {"hid", "namn", "malnummer", "beskrivning", "prioritet"};
            DefaultTableModel model = new DefaultTableModel (columnNames, 0);
            
            if (hallbarhetsLista == null || hallbarhetsLista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inga hållbarhetsmål hittades i databasen!");
            } else {
                for (HashMap<String, String> hallbarhetsmal : hallbarhetsLista){
                String hid = hallbarhetsmal.get("hid");
                String namn = hallbarhetsmal.get("namn");
                String malnumer = hallbarhetsmal.get ("malnummer");
                String beskrivning = hallbarhetsmal.get ("beskrivning");
                String prioritet = hallbarhetsmal.get("prioritet");
            model.addRow(new Object[] {hid, namn, malnumer, beskrivning, prioritet});
        }
    }
    tblHallbarhetsmal.setModel(model);
    } catch (InfException e) {
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av projektdata: " + e.getMessage());
        }  
    }
            
            
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hallbarhetsmalBild = new javax.swing.JLabel();
        tillbakaTillMeny = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHallbarhetsmal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hallbarhetsmalBild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hbild800x500.jpg"))); // NOI18N
        hallbarhetsmalBild.setText("jLabel1");
        hallbarhetsmalBild.setMaximumSize(new java.awt.Dimension(500, 500));
        hallbarhetsmalBild.setMinimumSize(new java.awt.Dimension(500, 500));

        tillbakaTillMeny.setBackground(new java.awt.Color(0, 102, 255));
        tillbakaTillMeny.setForeground(new java.awt.Color(255, 255, 255));
        tillbakaTillMeny.setText("TIllbaka till meny");
        tillbakaTillMeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tillbakaTillMenyActionPerformed(evt);
            }
        });

        tblHallbarhetsmal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Hid", "Namn", "Målnumer", "Beskrivning", "Prioritet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHallbarhetsmal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tillbakaTillMeny)
                    .addComponent(hallbarhetsmalBild, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(hallbarhetsmalBild, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(tillbakaTillMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tillbakaTillMenyActionPerformed
        this.setVisible(false);
        new Meny().setVisible(true);
    }//GEN-LAST:event_tillbakaTillMenyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hållbarhetsmål.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hållbarhetsmål().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hallbarhetsmalBild;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHallbarhetsmal;
    private javax.swing.JButton tillbakaTillMeny;
    // End of variables declaration//GEN-END:variables
}
    
       

