/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gui;
import orgEntities.Anstalld;
import db.*;
import logicComponents.User.*;
import oru.inf.InfDB;
import oru.inf.InfException;
import SQLHanterare.AnstalldHanterare;
import SQLHanterare.*;
import gui.projektfiler.OneProjectView;
import orgEntities.Projekt;


/**
 *
 * @author theow
 */
public class inloggning extends javax.swing.JFrame {
    
    private InfDB idb;
    private String ePost;
    private String losen;
    

    /** Creates new form inloggning */
    public inloggning() {
        
        idb = DatabaseInterface.databaseConnection();
        initComponents();
        setLocationRelativeTo(null);
        felUppgifter.setVisible(false);
        itemLoginAdmin.setText("Admin login");
        itemLoginHandlaggare.setText("Handläggare login");
        itemLoginProjChef.setText("Projektchef login");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        itemLoginAdmin = new javax.swing.JMenuItem();
        itemLoginProjChef = new javax.swing.JMenuItem();
        itemLoginHandlaggare = new javax.swing.JMenuItem();
        loginNamn = new javax.swing.JLabel();
        loginPW = new javax.swing.JLabel();
        epostField = new javax.swing.JTextField();
        pwField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        felUppgifter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDevMenu = new javax.swing.JButton();

        itemLoginAdmin.setText("jMenuItem1");
        itemLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginAdminActionPerformed(evt);
            }
        });
        jPopupMenu1.add(itemLoginAdmin);

        itemLoginProjChef.setText("jMenuItem1");
        itemLoginProjChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginProjChefActionPerformed(evt);
            }
        });
        jPopupMenu1.add(itemLoginProjChef);

        itemLoginHandlaggare.setText("jMenuItem1");
        itemLoginHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLoginHandlaggareActionPerformed(evt);
            }
        });
        jPopupMenu1.add(itemLoginHandlaggare);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 800));

        loginNamn.setText("E-post");

        loginPW.setText("Lösenord");

        loginButton.setText("Logga in");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        felUppgifter.setForeground(new java.awt.Color(204, 0, 51));
        felUppgifter.setText("Fel e-post eller lösenord.");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sdgswedenlogo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("LOGGA IN");

        btnDevMenu.setText("DevMenu2000");
        btnDevMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevMenuMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(felUppgifter)
                            .addComponent(loginButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginPW)
                                    .addComponent(loginNamn)
                                    .addComponent(jLabel2))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(epostField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDevMenu)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnDevMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(epostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginNamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPW)
                    .addComponent(pwField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(felUppgifter)
                .addGap(14, 14, 14)
                .addComponent(loginButton)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
      
        ePost = epostField.getText();
        losen = pwField.getText();
        
           
        if (ePost.isEmpty() || losen.isEmpty()) {                
            
            felUppgifter.setVisible(true);
            
        }
        else {
            
            try{
                String sqlFraga = "SELECT losenord FROM anstalld WHERE epost = " + "'" + ePost + "'";
                System.out.println(sqlFraga);
                String dbLosen = idb.fetchSingle(sqlFraga);
                if(losen.equals(dbLosen)){
                    
                    /* User assignment process: -> Creates object of anstalldhanterare which facilitates coms with DB 
                    -> creates anstalld object with anstalldhanterare object in parameter, which then populates fields of anstalld with db info 
                    -> creates user instance with anstalld object as field 
                    -> this user is set to current, and can then be referenced later in program. */
                    AnstalldHanterare anstalldHanterare = new AnstalldHanterare(ePost);
                    Anstalld anstalld = new Anstalld(anstalldHanterare);
                    User user = new User(anstalld);
                    CurrentUser.setUsr(user);
                    
                    
                    new Meny().setVisible(true);
                    this.setVisible(false);
                                       
                    
                    new OneProjectView("1").setVisible(true);
                    
                }
                else{
                    felUppgifter.setVisible(true);
                }
                
            } catch (Exception ex){
                System.out.println(ex.getMessage());
                
            }
            
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void btnDevMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevMenuMouseEntered
        jPopupMenu1.show(this,450, 80);
    }//GEN-LAST:event_btnDevMenuMouseEntered

    private void itemLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginAdminActionPerformed
        epostField.setText("maria.g@example.com");
        pwField.setText("password123");
        loginButtonActionPerformed(evt);
    }//GEN-LAST:event_itemLoginAdminActionPerformed

    private void itemLoginProjChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginProjChefActionPerformed
        epostField.setText("sofia.a@example.com");
        pwField.setText("passwordabc");
        loginButtonActionPerformed(evt);

    }//GEN-LAST:event_itemLoginProjChefActionPerformed

    private void itemLoginHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLoginHandlaggareActionPerformed
        epostField.setText("mohammed.ab@example.com");
        pwField.setText("passwordxyz");
        loginButtonActionPerformed(evt);

    }//GEN-LAST:event_itemLoginHandlaggareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new inloggning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevMenu;
    private javax.swing.JTextField epostField;
    private javax.swing.JLabel felUppgifter;
    private javax.swing.JMenuItem itemLoginAdmin;
    private javax.swing.JMenuItem itemLoginHandlaggare;
    private javax.swing.JMenuItem itemLoginProjChef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginNamn;
    private javax.swing.JLabel loginPW;
    private javax.swing.JTextField pwField;
    // End of variables declaration//GEN-END:variables

}
