/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import SQLHanterare.*;
import oru.inf.InfDB;
import oru.inf.InfException;
import db.DatabaseInterface;
import gui.Anställda;
import gui.Lander;
import gui.Meny;
import gui.projektfiler.EditProjectFields;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicComponents.User.CurrentUser;
import logicComponents.User.User;
import orgEntities.Land;
/**
 *
 * @author stina
 */
public class Lander extends javax.swing.JFrame {
    private InfDB idb;
    /**
     * Creates new form Partners
     * konstruktor
     */
    public Lander() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); // maximerar fönstret
        setLocationRelativeTo(null); // centrerar fönstret
        try {
        idb = DatabaseInterface.databaseConnection();
        fyllTabell(); // fyller tabellen
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Kunde inte ansluta till databasen");
    }
        tableMouseEvent();
    }
    
    // fyller tabellen från databasen
    private void fyllTabell(){
        try {
            String query = "SELECT * FROM land";
            ArrayList<HashMap< String, String >> landLista = idb.fetchRows(query);

            String [] columnNames = {"lid","namn","sprak","valuta","tidzon","politisk_struktur", "ekonomi", ""};
            DefaultTableModel model = new DefaultTableModel (columnNames, 0);
            
            if (landLista == null || landLista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inga länder hittades i databasen!");
            } else {
                for (HashMap<String, String> land : landLista){
              
                String lid = land.get("lid");
                String namn = land.get("namn");
                String sprak = land.get("sprak");
                String valuta = land.get("valuta");
                String tidszon = land.get("tidszon");
                String politiskStruktur = land.get("politisk_struktur");
                String ekonomi = land.get("ekonomi");
                
                
            model.addRow(new Object[] {lid, namn, sprak, valuta, tidszon, politiskStruktur, ekonomi, "Redigera"});
        }
    }
        tblLander.setModel(model);
    }   catch (InfException e) {
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av landdata: " + e.getMessage());
        }  
    }

    
    // // Lägger till en klick-lyssnare på tabelln, för redigering av land
    public void tableMouseEvent() {
        
        tblLander.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = tblLander.rowAtPoint(evt.getPoint());
        int col = tblLander.columnAtPoint(evt.getPoint());
        if (row >= 0 && col == 7) {
                
            Object varde = tblLander.getValueAt(row, 0);
            String lid = varde.toString();
            LandHanterare landHanterare = new LandHanterare(lid);
            Land land = new Land(landHanterare);
            new EditLand(land).setVisible(true);
            
 
            
            

            }
        }
    }
    );
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        parTillbakaTillMeny = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLander = new javax.swing.JTable();
        btnLaggTillLand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Länder:");

        parTillbakaTillMeny.setBackground(new java.awt.Color(0, 102, 255));
        parTillbakaTillMeny.setForeground(new java.awt.Color(255, 255, 255));
        parTillbakaTillMeny.setText("Tillbaka till meny");
        parTillbakaTillMeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parTillbakaTillMenyActionPerformed(evt);
            }
        });

        tblLander.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLander);

        btnLaggTillLand.setBackground(new java.awt.Color(0, 204, 0));
        btnLaggTillLand.setForeground(new java.awt.Color(255, 255, 255));
        btnLaggTillLand.setText("Lägg till land");
        btnLaggTillLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillLandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(parTillbakaTillMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLaggTillLand, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLaggTillLand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parTillbakaTillMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parTillbakaTillMenyActionPerformed
        this.setVisible(false);
        new Meny().setVisible(true);
    }//GEN-LAST:event_parTillbakaTillMenyActionPerformed

    private void btnLaggTillLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillLandActionPerformed
        new LaggTillLand().setVisible(true);
        
    }//GEN-LAST:event_btnLaggTillLandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lander.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anställda().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTillLand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton parTillbakaTillMeny;
    private javax.swing.JTable tblLander;
    // End of variables declaration//GEN-END:variables
}
