/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import oru.inf.InfDB;
import java.util.HashMap;
import logicComponents.User.CurrentUser;
import orgEntities.Anstalld;



/**
 *
 * @author agnesgaramvolgyi
 */
public class Meny extends javax.swing.JFrame {
    
    String namn = "";
    String CurrentUserAid = "";
    String CurrentUserRole = "";
    Anstalld currentAnstalld;

    /**
     * Creates new form Meny, and initialises its components.
     */
    public Meny() {
       
        currentAnstalld = CurrentUser.getUsr().getAnstalld();
        namn = currentAnstalld.getFornamn() + currentAnstalld.getEfternamn();
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        lblInloggadAnvandare.setText(namn);
        String aid = currentAnstalld.getAid();
        String role = currentAnstalld.getRole(aid);
        lblRole.setText(role);
        
        
        
        // TODO code printing of role name;
        
        
        /* this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        try {
        String sqlFraga = "SELECT * FROM anstalld WHERE epost = " + "'" + inloggadAnvandare + "'";
        HashMap<String, String> row = idb.fetchRow(sqlFraga);
        fornamn = row.get("fornamn");
        efternamn = row.get("efternamn");        
        lblInloggadAnvandare.setText("Hej " + fornamn + " " + efternamn + "!");
        
    
        
        } catch (Exception ex) {
                   } */
            
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        visaHallbarhetsmal = new javax.swing.JButton();
        visaProjekt = new javax.swing.JButton();
        LoggaUt = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setText("Namn");

        jLabel1.setText("Vad vill du göra idag?");

        visaHallbarhetsmal.setText("Hållbarhetsmål");
        visaHallbarhetsmal.setActionCommand("visaHallbarhetsmal");
        visaHallbarhetsmal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaHallbarhetsmalActionPerformed(evt);
            }
        });

        visaProjekt.setText("Projekt");
        visaProjekt.setActionCommand("visaProjekt");
        visaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaProjektActionPerformed(evt);
            }
        });

        LoggaUt.setText("Logga ut");
        LoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoggaUtActionPerformed(evt);
            }
        });

        lblRole.setText("Roll");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(visaHallbarhetsmal)
                        .addGap(39, 39, 39)
                        .addComponent(visaProjekt))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LoggaUt)))
                .addContainerGap(467, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRole))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblInloggadAnvandare)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblInloggadAnvandare)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblRole)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visaHallbarhetsmal)
                    .addComponent(visaProjekt))
                .addGap(39, 39, 39)
                .addComponent(LoggaUt)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visaHallbarhetsmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaHallbarhetsmalActionPerformed
        new Hållbarhetsmål().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_visaHallbarhetsmalActionPerformed

    private void visaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaProjektActionPerformed
        // göra samma sak som metoden över men med filnamn för projekt
    }//GEN-LAST:event_visaProjektActionPerformed

    private void LoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoggaUtActionPerformed
        this.dispose();
        inloggning inloggningForm = new inloggning();
        inloggningForm.setVisible(true);
    }//GEN-LAST:event_LoggaUtActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new Meny().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoggaUt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblRole;
    private javax.swing.JButton visaHallbarhetsmal;
    private javax.swing.JButton visaProjekt;
    // End of variables declaration//GEN-END:variables
}
