/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import oru.inf.InfDB;
import java.util.HashMap;
import logicComponents.User.*;
import orgEntities.Anstalld;



/**
 *
 * @author agnesgaramvolgyi
 */
public class Meny extends javax.swing.JFrame {
    
    String namn = "";
    String CurrentUserAid = "";
    String CurrentUserRole = "";
    Anstalld currentAnstalld;

    /**
     * Creates new form Meny, and initialises its components.
     */
    public Meny() {
       
        currentAnstalld = CurrentUser.getUsr().getAnstalld();
        namn = currentAnstalld.getFornamn() + " " + currentAnstalld.getEfternamn();
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        lblInloggadAnvandare.setText(namn);
        String aid = currentAnstalld.getAid();
        UserType userType = currentAnstalld.getRole(aid);
        lblRole.setText(userType.name());
        
        
        
        // TODO code printing of role name;
        
        
        /* this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        initComponents();
        try {
        String sqlFraga = "SELECT * FROM anstalld WHERE epost = " + "'" + inloggadAnvandare + "'";
        HashMap<String, String> row = idb.fetchRow(sqlFraga);
        fornamn = row.get("fornamn");
        efternamn = row.get("efternamn");        
        lblInloggadAnvandare.setText("Hej " + fornamn + " " + efternamn + "!");
        
    
        
        } catch (Exception ex) {
                   } */
            
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        visaHallbarhetsmal = new javax.swing.JButton();
        visaProjekt = new javax.swing.JButton();
        LoggaUt = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        visaAnställda = new javax.swing.JButton();
        visaAvdelning = new javax.swing.JButton();
        visaPartners = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggadAnvandare.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInloggadAnvandare.setForeground(new java.awt.Color(255, 255, 255));
        lblInloggadAnvandare.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblInloggadAnvandare.setText("Namn");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Välkommen!");

        visaHallbarhetsmal.setBackground(new java.awt.Color(0, 102, 255));
        visaHallbarhetsmal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        visaHallbarhetsmal.setForeground(new java.awt.Color(255, 255, 255));
        visaHallbarhetsmal.setText("Hållbarhetsmål");
        visaHallbarhetsmal.setActionCommand("visaHallbarhetsmal");
        visaHallbarhetsmal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaHallbarhetsmalActionPerformed(evt);
            }
        });

        visaProjekt.setBackground(new java.awt.Color(0, 102, 255));
        visaProjekt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        visaProjekt.setForeground(new java.awt.Color(255, 255, 255));
        visaProjekt.setText("Projekt");
        visaProjekt.setActionCommand("visaProjekt");
        visaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaProjektActionPerformed(evt);
            }
        });

        LoggaUt.setBackground(new java.awt.Color(0, 102, 255));
        LoggaUt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoggaUt.setForeground(new java.awt.Color(255, 255, 255));
        LoggaUt.setText("Logga ut");
        LoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoggaUtActionPerformed(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRole.setForeground(new java.awt.Color(255, 255, 255));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("Roll");

        visaAnställda.setBackground(new java.awt.Color(0, 102, 255));
        visaAnställda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        visaAnställda.setForeground(new java.awt.Color(255, 255, 255));
        visaAnställda.setText("Anställda");
        visaAnställda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaAnställdaActionPerformed(evt);
            }
        });

        visaAvdelning.setBackground(new java.awt.Color(0, 102, 255));
        visaAvdelning.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        visaAvdelning.setForeground(new java.awt.Color(255, 255, 255));
        visaAvdelning.setText("Avdelning");
        visaAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaAvdelningActionPerformed(evt);
            }
        });

        visaPartners.setBackground(new java.awt.Color(0, 102, 255));
        visaPartners.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        visaPartners.setForeground(new java.awt.Color(255, 255, 255));
        visaPartners.setText("Partners");
        visaPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaPartnersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(visaHallbarhetsmal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(visaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(visaAnställda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(visaAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(visaPartners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LoggaUt)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInloggadAnvandare, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRole)
                        .addGap(18, 18, 18)
                        .addComponent(LoggaUt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(visaHallbarhetsmal)
                        .addGap(30, 30, 30)
                        .addComponent(visaProjekt)
                        .addGap(35, 35, 35)
                        .addComponent(visaAnställda)
                        .addGap(32, 32, 32)
                        .addComponent(visaAvdelning)))
                .addGap(34, 34, 34)
                .addComponent(visaPartners)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visaHallbarhetsmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaHallbarhetsmalActionPerformed
        new Hållbarhetsmål().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_visaHallbarhetsmalActionPerformed

    private void visaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaProjektActionPerformed
        new projektruta().setVisible(true);
        this.setVisible(false);   
    }//GEN-LAST:event_visaProjektActionPerformed
  
    private void LoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoggaUtActionPerformed
        this.dispose();
        inloggning inloggningForm = new inloggning();
        inloggningForm.setVisible(true);
    }//GEN-LAST:event_LoggaUtActionPerformed

    private void visaAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaAvdelningActionPerformed
        new Avdelning().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_visaAvdelningActionPerformed

    private void visaAnställdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaAnställdaActionPerformed
        new Anställda().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_visaAnställdaActionPerformed

    private void visaPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaPartnersActionPerformed
        new Partners().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_visaPartnersActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new Meny().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoggaUt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInloggadAnvandare;
    private javax.swing.JLabel lblRole;
    private javax.swing.JButton visaAnställda;
    private javax.swing.JButton visaAvdelning;
    private javax.swing.JButton visaHallbarhetsmal;
    private javax.swing.JButton visaPartners;
    private javax.swing.JButton visaProjekt;
    // End of variables declaration//GEN-END:variables
}
