/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import SQLHanterare.*;
import orgEntities.*;
import oru.inf.InfDB;
import oru.inf.InfException;
import db.DatabaseInterface;
import gui.*;
import gui.anställdafiler.EditAnställda1;
import gui.anställdafiler.EditPartner;
import gui.anställdafiler.LäggTillPartner;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicComponents.User.CurrentUser;
import logicComponents.User.User;
/**
 *
 * @author stina
 */
public class Partners extends javax.swing.JFrame {
    
    private Partner partner; 
    private Partners partners;
    private InfDB idb;
    private String pid;
    private PartnerHanterare pah;
    
    /**
     * Creates new form Partners
     * konstruktor
     */
    public Partners() {
        partners = this;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); // maximerar fönstret
        setLocationRelativeTo(null); // centrerar fönstret
//        partner = this;
        try {
        idb = DatabaseInterface.databaseConnection();
        fyllTabell();
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Kunde inte ansluta till databasen");
        }
         try {
            this.tableMouseEvent(partners);
        } 
        catch (Exception e) {
        
            System.out.println(e);
        }
    }
    
    
        
       
        
    
   
    // fyller tabellen från databasen. 
    private void fyllTabell(){
        try {
            String query = "SELECT pid, namn, kontaktperson, kontaktepost, telefon, adress, branch, stad FROM partner";
            ArrayList<HashMap< String, String >> partnerLista = idb.fetchRows(query);

            String [] columnNames = {"pid", "namn", "kontaktperson", "kontaktepost", "telefon", "adress", "branch", "stad", "Redigera"};
            DefaultTableModel model = new DefaultTableModel (columnNames, 0);
            
            if (partnerLista == null || partnerLista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Inga partners hittades i databasen!");
            } else {
                for (HashMap<String, String> partner : partnerLista){
                String pid = partner.get("pid");
                String namn = partner.get("namn");
                String kontaktperson = partner.get ("kontaktperson");
                String kontaktepost = partner.get("kontaktepost");
                String telefon = partner.get("telefon");
                String adress = partner.get("adress");
                String branch = partner.get("branch");
                String stad = partner.get("stad");
                
            model.addRow(new Object[] {pid, namn, kontaktperson, kontaktepost, telefon, adress, branch, stad, "Redigera"});
        }
    }
        tblPartners.setModel(model);
    }   catch (InfException e) {
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av partnerdata: " + e.getMessage());
        }  
    }
    
    // Lägger till en klick-lyssnare på tabelln, för redigering av en partner
 public void tableMouseEvent(Partners partners) {
        
    tblPartners.addMouseListener(new java.awt.event.MouseAdapter() {
      @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = tblPartners.rowAtPoint(evt.getPoint());
            int col = tblPartners.columnAtPoint(evt.getPoint());
            if (row >= 0 && col == 8) {
                
                Object varde = tblPartners.getValueAt(row, 0);
                String pid = varde.toString();
                PartnerHanterare partnerHanterare = new PartnerHanterare(pid);
                Partner partner = new Partner(partnerHanterare);
                EditPartner editPartner = new EditPartner(partner);
                editPartner.setVisible(true);
//                partners.setVisible(true);
            
            }
        }
    }
    );    
 }
    
    // ta bort partner
    public void removePartner(String pid) {
        
        if (new PartnerHanterare().taBortPartner(pid)) {
            JOptionPane.showMessageDialog(rootPane, "Partner borttagen.");
            fyllTabell();
            
        } 
        else {
            JOptionPane.showMessageDialog(rootPane, "Kunde inte ta bort partner.");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        parTillbakaTillMeny = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartners = new javax.swing.JTable();
        bnLaggTillPartner = new javax.swing.JButton();
        bnTaBortPartner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Partners:");

        parTillbakaTillMeny.setBackground(new java.awt.Color(0, 102, 255));
        parTillbakaTillMeny.setForeground(new java.awt.Color(255, 255, 255));
        parTillbakaTillMeny.setText("Tillbaka till meny");
        parTillbakaTillMeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parTillbakaTillMenyActionPerformed(evt);
            }
        });

        tblPartners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPartners);

        bnLaggTillPartner.setBackground(new java.awt.Color(0, 204, 0));
        bnLaggTillPartner.setForeground(new java.awt.Color(255, 255, 255));
        bnLaggTillPartner.setText("Lägg till partner");
        bnLaggTillPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnLaggTillPartnerActionPerformed(evt);
            }
        });

        bnTaBortPartner.setBackground(new java.awt.Color(204, 0, 0));
        bnTaBortPartner.setForeground(new java.awt.Color(255, 255, 255));
        bnTaBortPartner.setText("Ta bort partner");
        bnTaBortPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnTaBortPartnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(parTillbakaTillMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bnTaBortPartner)
                            .addGap(18, 18, 18)
                            .addComponent(bnLaggTillPartner))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 995, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parTillbakaTillMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnLaggTillPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnTaBortPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parTillbakaTillMenyActionPerformed
        this.setVisible(false);
        new Meny().setVisible(true);
    }//GEN-LAST:event_parTillbakaTillMenyActionPerformed

    private void bnLaggTillPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnLaggTillPartnerActionPerformed
         new LäggTillPartner().setVisible(true);
//         this.setVisible(false);
    }//GEN-LAST:event_bnLaggTillPartnerActionPerformed

    private void bnTaBortPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnTaBortPartnerActionPerformed
 
        // kontrollerar om en rad i tabellen är vald, om ja anropas removePartner(pid) för att ta bort partnern. 
        int selectedRow = tblPartners.getSelectedRow();
        if (selectedRow == -1) {
            
            System.out.println("Ingen vald rad");
              return;
        }
          int column = 0; 
          
          String pid = (String) tblPartners.getValueAt(selectedRow, column);

     
            
       if (JOptionPane.showConfirmDialog(rootPane, "Är du säker på att du vill ta bort partnern?") == JOptionPane.YES_OPTION ) {
            
                removePartner(pid);
            }
                      
        
            
         
    }//GEN-LAST:event_bnTaBortPartnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partners().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnLaggTillPartner;
    private javax.swing.JButton bnTaBortPartner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton parTillbakaTillMeny;
    private javax.swing.JTable tblPartners;
    // End of variables declaration//GEN-END:variables
}
