package gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import orgEntities.Anstalld;
import db.DatabaseInterface;
import gui.Meny;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import logicComponents.User.CurrentUser;
import logicComponents.User.UserType;

/**
 *
 * @author amandahelinlarsson
 */
public class projektruta extends javax.swing.JFrame {
    private InfDB idb;
    
private Anstalld currentAnstalld;    
    
 public projektruta(){
    initComponents(); 
    setExtendedState(MAXIMIZED_BOTH);
    setLocationRelativeTo(null);
try {
    idb = DatabaseInterface.databaseConnection();
fyllTabell();
} catch (Exception e){
   
}
if (CurrentUser.getUsr() !=null) {
UserType userType = CurrentUser.getUsr().getUserType();
String userTypeString = userType.toString();
} else {

}
 }
    
private void fyllTabell(){
try {
    String query = "";
    currentAnstalld = CurrentUser.getUsr().getAnstalld();
    String aid = currentAnstalld.getAid();
    UserType userType = currentAnstalld.getRole(aid);
     
    if (userType == UserType.handlaggare){
         query = "SELECT pid, projektnamn, beskrivning, startdatum, slutdatum, kostnad, prioritet, status" +
                    "FROM projekt WHERE handlaggare_id = '" + aid + "'";
    } else if (userType == UserType.admin1 || userType == UserType.admin2){
    query = "SELECT pid, projektnamn, beskrivning, startdatum, slutdatum, kostnad, prioritet, status FROM projekt";
        } 
    
ArrayList<HashMap< String, String >> projektlista = idb.fetchRows(query);
System.out.println("Antal projekt hämtade:" + projektlista.size());
String [] columnNames = {"pid", "projektnamn", "beskrivning", "startdatum", "slutdatum", "kostnad", "prioritet", "status"};
DefaultTableModel model = new DefaultTableModel (columnNames, 0);
for (HashMap<String, String> projekt : projektlista){
String pid = projekt.get("pid");
String namn = projekt.get("projektnamn");
String beskrivning = projekt.get ("beskrivning");
String start = projekt.get ("startdatum");
String slut = projekt.get ("slutdatum");
String prioritet = projekt.get("prioritet");
String kostnad = projekt.get ("kostnad"); 
String status = projekt.get ("status");
model.addRow(new Object[] {pid, namn, beskrivning, start, slut, kostnad, prioritet, status});
}
tblProjekt.setModel(model);
} catch (InfException e) {
JOptionPane.showMessageDialog(this, "Fel vid hämtning av projektdata: " + e.getMessage());
}
}


private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
String searchText = jTextField1.getText().toLowerCase();
DefaultTableModel model = (DefaultTableModel) tblProjekt.getModel();
DefaultTableModel filteredModel = new DefaultTableModel(
new String [] {"pid", "projektnamn", "beskrivning", "startdatum", "sludatum", "kostnad", "prioritet", "status"}, 0
);
for (int i = 0; 1 < model.getRowCount(); i++) {
String projectName = model.getValueAt(i, 1).toString().toLowerCase();
if (projectName.contains(searchText)){
filteredModel.addRow(new Object[]{
model.getValueAt(i, 0), model.getValueAt(i, 1), model.getValueAt(i, 2),
model.getValueAt(i, 3), model.getValueAt(i, 4), model.getValueAt(i, 5),
model.getValueAt(i, 6), model.getValueAt(i, 7)
});
}
}
tblProjekt.setModel(filteredModel); 
}


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        proTillbakaTillMeny = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProjekt = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Partners");

        jLabel1.setText("Projekt");

        proTillbakaTillMeny.setText("Tillbaka till meny");
        proTillbakaTillMeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proTillbakaTillMenyActionPerformed(evt);
            }
        });

        tblProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "pid", "projektnamn", "beskrivning", "Startdatum", "slutdatum", "kostnad", "prioritet", "status"
            }
        ));
        jScrollPane1.setViewportView(tblProjekt);

        jLabel2.setText("Sök projekt");

        jButton1.setText("Sök");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< Updated upstream
<<<<<<< Updated upstream
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
=======
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
>>>>>>> Stashed changes
=======
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
>>>>>>> Stashed changes
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(proTillbakaTillMeny)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
<<<<<<< Updated upstream
<<<<<<< Updated upstream
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 886, Short.MAX_VALUE)
                                .addComponent(jButton3)))
                        .addGap(270, 270, 270))))
=======
=======
>>>>>>> Stashed changes
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 904, Short.MAX_VALUE)
                                .addComponent(jButton3)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102))
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
<<<<<<< Updated upstream
<<<<<<< Updated upstream
                    .addComponent(jButton3))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(proTillbakaTillMeny)
                .addContainerGap(101, Short.MAX_VALUE))
=======
=======
>>>>>>> Stashed changes
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(645, 645, 645)
                        .addComponent(proTillbakaTillMeny))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> Stashed changes
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proTillbakaTillMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proTillbakaTillMenyActionPerformed
        this.setVisible(false);
        new Meny().setVisible(true);
    }//GEN-LAST:event_proTillbakaTillMenyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projektruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projektruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projektruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projektruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projektruta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton proTillbakaTillMeny;
    private javax.swing.JTable tblProjekt;
    // End of variables declaration//GEN-END:variables
}


